### ISSUE TITLE
Wrong/duplicated shortcut iCloud link.

### ISSUE THREAD

**Issue by JiamingSuen** [adamtow/control-blackmagic-cam-shortcuts#1]
Hi Adam @adamtow , thanks for this amazing repo and the accompanying blog post! I noticed that some of the shortcut links in your blog post are not working (cannot be added to iPhone) and found this repo after some digging. I found some (4 out of 14) shortcut links are wrong. For example, https://github.com/adamtow/control-blackmagic-cam-shortcuts/blob/7b152a6f1bb21c76290a7e25de0cf88e575cfaea/docs/_shortcuts/control-blackmagic-cam-record.md?plain=1#L6 should be the 'Start Record' shortcut but the iCloud link points to the 'View' shortcut.

<img width="1065" alt="image" src="https://github.com/adamtow/control-blackmagic-cam-shortcuts/assets/8616975/c8ec6d37-3527-4f80-862e-1e8b37a9bae0">

Would you please fix those links? Thanks very much!

**Comment by adamtow** [comment]
Thanks for the report. I've updated the underlying links to the shortcuts.
